---
hero-title: Aaron Conway BN (Hons) PhD
hero-subtitle: |
  RBC Chair in Cardiovascular Nursing Research | Peter Munk Cardiac   Centre<br>Assistant Professor | Lawrence S. Bloomberg Faculty of Nursing | University of Toronto
output: 
  myrmdtemplate::bloomberg:
    toc: true
    toc_float: true
params:
  orcid.id: "0000-0002-9583-8636"
  years.since: 2010
  spacer: ', '
  journal.only: "Yes"
  order: "dyear"
  max.authors: 3
  style: "APA"
  bullets: 'numbers'
  extra.order: 'None'
  flag.OA: FALSE
  bold.author: FALSE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(scholar)
library(kableExtra)
library(cvR)
library(plotly)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, results = 'asis')
library(rorcid)
x  <- "dc7ea3ae-38fd-4188-8bd1-1db4215ea139"
Sys.setenv(ORCID_TOKEN=x, orcid_email="aaron.conway@utoronto.ca")
```


# <i class="fas fa-book fa-fw"></i> Publications
```{r}
id <- "2hpmnr8AAAAJ"

## Get his profile
l <- get_profile(id)
```

```{r}
scholar <- scholar::get_publications(id) 
scholar$journal <- recode(scholar$journal, "The Cochrane Library" = "Cochrane Database of Systematic Reviews")
```

```{r}
papers <- get_num_articles(id)
journals  <- get_num_distinct_journals(id)
```

<br>
<div class="row">
<div class="col-md-4">
<div class = "box">
<span style="font-size: 32px;">
`r papers`<br>
</span>
articles
</div>
</div>
<div class="col-md-4">
<div class = "box">
<span style="font-size: 32px;">
`r l$total_cites`<br>
</span>
citations
</div>
</div>
<div class="col-md-4">
<div class = "box">
<span style="font-size: 32px;">
`r l$h_index`<br>
</span>
h-index
</div>
</div>
</div>

<br>
<div class="row">
<div class="col-md-6">
```{r pubs, out.width="90%"}
pubs_plot <- scholar %>% 
  group_by(year) %>% 
  summarise(pubsperyear = n()) %>% 
  mutate(total = cumsum(pubsperyear)) %>% 
  ggplot(aes(year, total)) +
  geom_line(size=1, color='darkgrey') +
  geom_point(size=3, color="#284260") +
  theme_classic() +
  labs(x= "Year", y = "Publications") +
  scale_x_continuous(breaks = seq(2010, max(scholar$year, na.rm = TRUE), by=2))+
  theme(axis.title  =element_text(face = "bold", size=16))
ggplotly(pubs_plot)
```
</div>
<div class="col-md-6">
```{r cites, out.width="90%"}
ct <- get_citation_history(id)

## Plot citation trend
citations_plot <- ggplot(ct, aes(year, cites)) +
  geom_segment(aes(xend = year, yend = 0), size=1, color='darkgrey') +
  geom_point(size=3, color="DarkSlateGray") +
  theme_classic() +
  labs(x= "Year", y = "Citations")+
    theme(axis.title  =element_text(face = "bold", size=16))
ggplotly(citations_plot)

```
</div>
</div>

# <i class="fas fa-computer-classic fa-fw"></i> Software

```{r}
software <- tribble(~package, ~description, ~year,
                    "spiritR", "A workflow to enable direct upload of a clinical trial protocol to clinicaltrials.gov
", 2019)

glue::glue('<br>
  <ul style="list-style-type:none;">
  <li>
  <a href="https://spiritr.netlify.com"><em>{software$package}</em></a><br>{software$description} <span style="float:right;">{software$year}</span>
  </li>
  </ul>')
```
