on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'

name: render

jobs:
  render:
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    
    - name: Install scholar
      run: Rscript -e 'install.packages("scholar")'
      
    - name: Install rorcid
      run: Rscript -e 'install.packages("rorcid")'
      
    - name: Install kableExtra
      run: Rscript -e 'install.packages("kableExtra")'

    - name: Install curl
      run: Rscript -e 'install.packages("curl")'
      
    - name: Install rcrossref
      run: Rscript -e 'install.packages("rcrossref")'
      
    - name: render rmarkdown  
      run: Rscript -e 'rmarkdown::render("index.Rmd")'
      
    - name: Upload results
      uses: actions/upload-artifact@master
      with:
        name: docs
        path: index.html

  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: render
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@v1
        with: 
          name: docs
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.actions }} # https://github.com/settings/tokens
          BRANCH: master # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
