on:  
 schedule:
     # * is a special character in YAML so you have to quote this string
     - cron:  '10 15 * * *'

name: render

jobs:
  render:
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    
    - name: Install scholar
      run: Rscript -e 'install.packages("scholar")'
      
    - name: Install rorcid
      run: Rscript -e 'install.packages("rorcid")'
      
    - name: Install kableExtra
      run: Rscript -e 'install.packages("kableExtra")'

    - name: Install curl
      run: Rscript -e 'install.packages("curl")'
      
    - name: Install rcrossref
      run: Rscript -e 'install.packages("rcrossref")'

    - name: Install myrmdtemplate
      run: Rscript -e 'devtools::install_github("awconway/myrmdtemplate")'
      
    - name: Install cvR
      run: Rscript -e 'devtools::install_github("awconway/cvR")'
      
    - name: render rmarkdown  
      run: Rscript -e 'rmarkdown::render("index.Rmd")'
      
    - name: Upload results
      uses: actions/upload-artifact@master
      with:
        name: docs
        path: index.html

  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: render
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@master
        with: 
          name: docs
      - name: push
        run: |
           REMOTE=https://${{ secrets.actions }}@github.com/${{ github.repository }}
           git config user.email "${{ github.actor }}@users.noreply.github.com"
           git config user.name "${{ github.actor }}"
           git pull ${REMOTE}
           git checkout master
           git add .
           git status
           git commit -am "Scheduled"
           git push ${REMOTE} master
        
  build:
      name: netlify
      needs: [render, checkout-and-deploy]
      runs-on: ubuntu-latest
      steps:
      - name: Trigger our build webhook on Netlify
        run: curl -s -X POST "https://api.netlify.com/build_hooks/${netlify_build_token}"
        env:
          TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
