on: 
 schedule:
    #  * is a special character in YAML so you have to quote this string
    - cron:  '0 14 * * *'

name: render

jobs:
  render:
    runs-on: ubuntu-latest
    container: awconway/schedulecv
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
      
    - name: render rmarkdown  
      env:
        ORCID_TOKEN: ${{ secrets.ORCID_TOKEN }}
      run: Rscript -e 'rmarkdown::render("index.Rmd")'
      
    - name: Upload results
      uses: actions/upload-artifact@master
      with:
        name: docs
        path: index.html

  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: render
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@master
        with: 
          name: docs
      - name: push
        run: |
           REMOTE=https://${{ secrets.actions }}@github.com/${{ github.repository }}
           git config user.email "${{ github.actor }}@users.noreply.github.com"
           git config user.name "${{ github.actor }}"
           git pull ${REMOTE}
           git checkout master
           git add .
           git status
           git commit -am "Scheduled"
           git push ${REMOTE} master
